### PR TITLE
Next generation lunch recording technology. 

### PR DESCRIPTION
**Pull request by guncha**
1) Refactored implementation details into a Lunch class
2) Made harder for people to accidentally re-seed the data (this will need to be run since the format has changed)

Personality adjustments are up to you!

### CODE REVIEW

**Comment by chanks** [comment]
Thanks! Jamie voices his appreciation too, but is without Internet access
at the moment :)

**Comment by NevilleS** [comment]
:+1: :smile: :+1:

:hamburger: :pizza: :meat_on_bone: :rice: :yum:

**Comment by jhdavids8** [comment]
@NevilleS Just tried it locally and it looks good to me! I'll let you merge though since you have to deploy (I think)...

**Comment by NevilleS** [comment]
IT'S LIVE

**Pull request merged**
